name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
      runs-on: ubuntu-latest

      steps:
        - name: Set RELEASE_VERSION
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        - name: Release draft
          uses: release-drafter/release-drafter@v5
          with:
            name: ${{ env.RELEASE_VERSION }}
            tag: ${{ env.RELEASE_VERSION }}
            version: ${{ env.RELEASE_VERSION }}
            publish: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}