name: Sync new version to repo

on:
  push:
#    tags:
#      - v*

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: hanialshikh/kodi
          ssh-key: ${{ secrets.BOT_DEPLOY_KEY }}

      - name: Pull & update submodules recursively
        run: |
          echo ${{ secrets.BOT_DEPLOY_KEY }} > key
          GIT_SSH_COMMAND='ssh -i key -o IdentitiesOnly=yes'
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          echo ${{ secrets.BOT_DEPLOY_KEY }} > key
          GIT_SSH_COMMAND='ssh -i key -o IdentitiesOnly=yes'
          git config user.email "deploy-bot@no-replay.github.com"
          git config user.name "Deploy Bot"
          git add --all
          git commit -m "Update H-S videos to ${${GITHUB_REF##*/}:1}" || echo "No changes to commit"
          git push